version: '3'

services:
  esports_api:
    build: .
    volumes:
      - .:/go/src/
    ports:
      - "8030:8030"
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
     - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
      
volumes:
  data: